### ISSUE TITLE
just run Window have install NET

### ISSUE THREAD

**Issue by 1sn0m4d** [Ch0pin/AVIator#7]
No run Win7 system 

if the system not have install net 2.0 ,3.0 or net 4.0

**Comment by Ch0pin** [comment]
You have to install the latest Net framework or at least 4.0 and above

**Comment by 1sn0m4d** [comment]
helllo sir 

cloud you add   support net 3.5 working ..

have a nice day

**Comment by Ch0pin** [comment]
Do you have the Net framework 3.5 installed and it doesn't run or doesn't compile ?
